schema_version: 1

context:
  name: lammpsparser
  version: "0.0.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lammpsparser-${{ version }}.tar.gz
  sha256: e0eb79e82b9257902b99a8249332dea1946cebb15c78d371de9f0f847e411b4f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - scipy
    - ase
    - numpy
    - pandas
  run:
    - python >=${{ python_min }}
    - scipy >=1.11.1,<=1.17.1
    - ase >=3.22.1,<=3.28.0
    - numpy >=1.26.0,<=2.4.6
    - pandas >=2.0.3,<=3.0.3
tests:
  - python:
      imports:
        - lammpsparser
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Parser for LAMMPS input and output files.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/lammpsparser

extra:
  recipe-maintainers:
    - jan-janssen
